data:
  random_state: 42
  train_file: project/data/train.csv
  test_file: project/data/test.csv
  test_size: 0.2
  target: target_column
  features: ["feature1", "feature2", "feature3"]
models:
  logistic_regression:
    random_state: 42
    max_iter: 1000
  random_forest:
    random_state: 42
    n_estimators: 100
preprocessing:
  numeric_features: ["feature1", "feature2"]
  numeric_transformer:
    imputer_strategy: "median"
  categorical_features: ["feature3"]
  categorical_transformer:
    imputer_strategy: "most_frequent"
evaluation:
  cross_validation:
    cv: 5
    scoring: accuracy
output:
  model_path: ../project/outputs/models
  submission_path: ../project/outputs/submissions
