data.train_file: train.csv
data.test_file: test.csv
data.features: ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
data.target: Survived
data.test_size: 0.2
data.random_state: 42
preprocessing.numeric_features: ["Age", "SibSp", "Parch", "Fare"]
preprocessing.numeric_transformer.imputer_strategy: median
preprocessing.categorical_features: ["Pclass", "Sex", "Embarked"]
preprocessing.categorical_transformer.imputer_strategy: most_frequent
models.logistic_regression.max_iter: 1000
models.logistic_regression.random_state: 42
models.random_forest.n_estimators: 100
models.random_forest.random_state: 42
evaluation.cross_validation.cv: 5
evaluation.cross_validation.scoring: accuracy
output.model_path: models
output.submission_path: submissions
