data:
  random_state: 42
  train_file: data/train.csv
  test_file: data/test.csv
  test_size: 0.2
  target: Survived
  features: [Pclass, Sex, Age, SibSp, Parch, Fare, Embarked]
  
models:
  logistic_regression:
    random_state: 42
    max_iter: 1000
  random_forest:
    random_state: 42
    n_estimators: 100

preprocessing:
  numeric_features: [Age, SibSp, Parch, Fare]
  categorical_features: [Pclass, Sex, Embarked]
  numeric_transformer:
    imputer_strategy: mean
  categorical_transformer:
    imputer_strategy: most_frequent

evaluation:
  cross_validation:
    cv: 5
    scoring: accuracy

output:
  model_path: outputs/models
  submission_path: outputs/submissions